# TODO Вызовите ошибку AssertionError с собственным текстом


raise ValueError('Произола другая ошибка')
raise AssertionError('Произошла ошибка!')
